name: Mobile Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install --legacy-peer-deps

      - name: Install Expo & EAS
        run: |
          bunx expo --version
          bunx eas --version

      - name: Build Android APK
        run: bunx eas build -p android --profile preview --non-interactive --json > apk.json
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android AAB
        run: bunx eas build -p android --profile production --non-interactive --json > aab.json
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download Android artifacts
        run: |
          VERSION=${GITHUB_REF_NAME}

          APK_URL=$(jq -r '.[0].artifacts.buildUrl' apk.json)
          AAB_URL=$(jq -r '.[0].artifacts.buildUrl' aab.json)

          curl -L "$APK_URL" -o "Skewlapp-${VERSION}-android.apk"
          curl -L "$AAB_URL" -o "Skewlapp-${VERSION}-android.aab"

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            Skewlapp-${{ github.ref_name }}-android.apk
            Skewlapp-${{ github.ref_name }}-android.aab

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-android]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files
        run: find . -type f

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.apk
            **/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}